services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres-traceabilitytools
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres-traceabilitytools-data:/var/lib/postgresql/data
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/01-postgres-init.sql:ro
    restart: unless-stopped

volumes:
  postgres-traceabilitytools-data:
